# Generated by Django 3.2.6 on 2022-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_column='type', verbose_name='Тип комплектуещего')),
                ('name', models.TextField(db_column='name', verbose_name='Наиминование')),
                ('price', models.IntegerField(db_column='price', verbose_name='Цена')),
                ('year', models.IntegerField(db_column='year', verbose_name='Год выпуска')),
                ('owner', models.TextField(db_column='owner', verbose_name='Производитель')),
                ('count', models.IntegerField(db_column='count', verbose_name='количество')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
    ]
